### ISSUE TITLE
To do requests

### ISSUE THREAD

**Issue by dick-ey** [dick-ey/Yosemite-Mobile#4]
-Yahoo Weather
-Snapchat
-Twitter
-Instagram
-Netflix
-Movie Box (arggggh, matey)
-iFunny

**Comment by billyker** [comment]
Hi Matt,

Added Yahoo Weather, Twitter and Netflix Icons..

=)
Billy

**Comment by dick-ey** [comment]
Closing this issue since repo is no longer under active development.
